// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUFi32BEcPCZ_KOuhSGAT5S6sHduBmp_I',
    appId: '1:438554090273:web:559850cdd372dbfbaf7c60',
    messagingSenderId: '438554090273',
    projectId: 'todo-9ef6e',
    authDomain: 'todo-9ef6e.firebaseapp.com',
    storageBucket: 'todo-9ef6e.appspot.com',
    measurementId: 'G-SFKXJFLHPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEYuiG1c7fBWq9VbkmRc-UtzJDaBguMhQ',
    appId: '1:438554090273:android:e9cda197a437f89baf7c60',
    messagingSenderId: '438554090273',
    projectId: 'todo-9ef6e',
    storageBucket: 'todo-9ef6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD914FLm4WJ6ycWJyIMnTEVXbJUkcKw6E',
    appId: '1:438554090273:ios:c95afd7e6c317315af7c60',
    messagingSenderId: '438554090273',
    projectId: 'todo-9ef6e',
    storageBucket: 'todo-9ef6e.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD914FLm4WJ6ycWJyIMnTEVXbJUkcKw6E',
    appId: '1:438554090273:ios:7e8e64ca427b86a6af7c60',
    messagingSenderId: '438554090273',
    projectId: 'todo-9ef6e',
    storageBucket: 'todo-9ef6e.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
